#!/usr/bin/env node
/**
 * build_graph_svg.mjs — authoring-time graph pre-render script
 *
 * Reads:
 *   - site/src/data/vaults_graph.mmd  (Mermaid DSL; itself generated by build_vaults_data.mjs)
 *   - site/src/data/vaults.json       (for the accessible title/desc counts)
 *
 * Writes:
 *   - site/src/assets/vaults_graph.svg (pre-rendered static SVG; committed)
 *
 * Renders the .mmd → SVG ONCE at authoring time, using the local mermaid bundle inside a
 * Playwright-chromium page (fully offline — no CDN, strict securityLevel → CSP-safe output),
 * then post-processes for the site:
 *   - real <text> labels (htmlLabels:false) so the graph text is selectable + machine-readable;
 *   - strip fixed width/height → viewBox + max-width:100% (scales to its container);
 *   - role="img" + <title>/<desc> (one labelled image; the /vaults/graph node-list is the
 *     keyboard/AT navigation twin);
 *   - theme post-processing: edges, arrowheads, and the orphan cluster inherit `currentColor`
 *     (+ the page's --color-text) so the graph reads on BOTH the dark (default, Tokyo Night)
 *     and light canvases. Node chips keep their self-grounding light fill + black text (drawn
 *     from the .mmd classDefs), which read on either canvas unchanged.
 *
 * The page inlines the committed SVG via a Vite `?raw` import (zero runtime JS). CI/Vercel
 * builds consume the committed artifact — this script never runs in CI (mirrors ADR-023
 * Clause A: regen at authoring time; the build uses the last-committed output). No new
 * dependency + no new build step: mermaid + @playwright/test are already in site/.
 *
 * Idempotency: deterministic (fixed svg id, deterministic dagre layout). Writes only when the
 * post-processed output differs from the committed file — a byte-identical render is a no-op.
 *
 * Usage (from site/):  npm run sync:graph
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, '..');
const SITE = path.join(PROJECT_ROOT, 'site');
const MMD = path.join(SITE, 'src/data/vaults_graph.mmd');
const VAULTS_JSON = path.join(SITE, 'src/data/vaults.json');
const MERMAID_MIN = path.join(SITE, 'node_modules/mermaid/dist/mermaid.min.js');
const OUTPUT_SVG = path.join(SITE, 'src/assets/vaults_graph.svg');

// Stable svg id — used as the element id, the marker-id prefix, and the scope of mermaid's
// embedded <style>. MUST be fixed (not random) for byte-identical idempotency.
const SVG_ID = 'vaultsGraph';

// --- Authoring-time guards (skip cleanly; never clobber the committed artifact) --------------
if (!fs.existsSync(MMD)) {
  console.warn(`[build_graph_svg] WARN: ${MMD} not present; keeping last-committed vaults_graph.svg.`);
  process.exit(0);
}
if (!fs.existsSync(MERMAID_MIN)) {
  console.warn(`[build_graph_svg] WARN: mermaid bundle not found at ${MERMAID_MIN}; run \`npm install\` in site/. Keeping last-committed vaults_graph.svg.`);
  process.exit(0);
}

// Playwright is a site/ devDependency — resolve it from there. Absent (e.g. a production-only
// install) → skip, mirroring the sibling scripts' CI/Vercel fallback posture.
const requireFromSite = createRequire(path.join(SITE, 'package.json'));
let chromium;
try {
  ({ chromium } = requireFromSite('@playwright/test'));
} catch {
  console.warn('[build_graph_svg] WARN: @playwright/test not installed in site/; keeping last-committed vaults_graph.svg. (Authoring-time only; CI uses the committed artifact.)');
  process.exit(0);
}

const chart = fs.readFileSync(MMD, 'utf-8');

// htmlLabels:false renders real, selectable <text> but does NOT interpret HTML tags inside a
// label. The .mmd label markup is `Name<br><sub>persona</sub>`: mermaid's text renderer honours
// <br> (a line break — kept) but would print <sub>…</sub> literally. Strip the <sub> wrappers,
// leaving the persona on its own <br> line. The committed .mmd is untouched — this transforms
// only the string handed to the renderer.
const renderChart = chart.replace(/<\/?sub>/g, '');

// Accessible counts — from vaults.json when present, else parsed from the .mmd as a fallback.
let vaultCount = null;
let edgeCount = null;
if (fs.existsSync(VAULTS_JSON)) {
  try {
    const data = JSON.parse(fs.readFileSync(VAULTS_JSON, 'utf-8'));
    vaultCount = data.vault_count ?? (Array.isArray(data.vaults) ? data.vaults.length : null);
    edgeCount = Array.isArray(data.edges) ? data.edges.length : null;
  } catch (e) {
    console.warn(`[build_graph_svg] WARN: vaults.json parse failed (${e.message}); deriving counts from the .mmd.`);
  }
}
if (vaultCount == null) {
  // node ids are `id["label"]` lines; count them (both top-level + subgraph).
  vaultCount = (chart.match(/^\s*\w[\w]*\["/gm) || []).length;
}
if (edgeCount == null) {
  edgeCount = (chart.match(/(-->|==>|-\.->|--o|--x)/g) || []).length;
}

const titleText = `aDNA vault network topology — ${vaultCount} vaults, ${edgeCount} edges`;
const descText = `A directed graph of the aDNA network: ${vaultCount} vaults joined by ${edgeCount} cited relationships (umbrella, federation, partner, companion, supersedes). Vaults with no cited relationship yet sit in the "not yet linked" holding area. Each box names a vault and its persona; the accompanying vault list is the keyboard-navigable twin.`;

function xmlEscape(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// --- Render offline --------------------------------------------------------------------------
const browser = await chromium.launch();
let rawSvg;
try {
  const page = await browser.newPage();
  await page.setContent('<!doctype html><html><head></head><body><div id="host"></div></body></html>');
  await page.addScriptTag({ path: MERMAID_MIN });
  rawSvg = await page.evaluate(async ({ chartSrc, svgId }) => {
    // The esbuild IIFE exposes the module at window.__esbuild_esm_mermaid_nm.mermaid.default.
    const ns = window.__esbuild_esm_mermaid_nm;
    const mermaid = ns && ns.mermaid && ns.mermaid.default ? ns.mermaid.default : window.mermaid;
    if (!mermaid || typeof mermaid.render !== 'function') throw new Error('mermaid global not found after injecting the local bundle');
    mermaid.initialize({
      startOnLoad: false,
      securityLevel: 'strict',      // no inline handlers/scripts in output → CSP-safe to inline
      theme: 'base',
      htmlLabels: false,            // real <svg text>, not <foreignObject> HTML → selectable
      flowchart: { htmlLabels: false, useMaxWidth: true },
      fontFamily: "'Space Grotesk', system-ui, sans-serif",
    });
    const { svg } = await mermaid.render(svgId, chartSrc);
    return svg;
  }, { chartSrc: renderChart, svgId: SVG_ID });
} finally {
  await browser.close();
}

// --- Post-process ----------------------------------------------------------------------------
let svg = rawSvg;

// 1) Preserve the viewBox; rebuild the root <svg> tag deterministically (role=img, no fixed
//    width/height, max-width:100%, labelled by the injected title+desc).
const vbMatch = svg.match(/viewBox="([^"]+)"/);
const viewBox = vbMatch ? vbMatch[1] : '0 0 800 600';
const titleId = `${SVG_ID}-title`;
const descId = `${SVG_ID}-desc`;
const openTag =
  `<svg id="${SVG_ID}" xmlns="http://www.w3.org/2000/svg" class="flowchart" ` +
  `viewBox="${viewBox}" role="img" aria-labelledby="${titleId} ${descId}" ` +
  `style="max-width:100%;height:auto">`;
const titleDesc =
  `<title id="${titleId}">${xmlEscape(titleText)}</title>` +
  `<desc id="${descId}">${xmlEscape(descText)}</desc>`;

// Replace everything up to and including the original opening <svg ...> tag.
svg = svg.replace(/^[\s\S]*?<svg[^>]*>/, openTag + titleDesc);

// 2) Append a theme-adaptation <style> just before </svg>. All of mermaid's own colour rules are
//    id-scoped without !important, so these id-scoped !important rules win the cascade.
//    Node chips + node label text carry inline `!important` fills from the .mmd classDefs and are
//    deliberately left untouched (they are self-grounding on either canvas).
const themeStyle = `<style>
/* Theme adaptation (build_graph_svg.mjs) — edges/arrowheads/cluster follow the page text colour
   so the graph reads on both the dark (default) and light canvases. */
#${SVG_ID}{color:var(--color-text,#c0caf5);}
#${SVG_ID} .flowchart-link{stroke:currentColor !important;}
#${SVG_ID} .marker,#${SVG_ID} .marker path,#${SVG_ID} .arrowMarkerPath{fill:currentColor !important;stroke:currentColor !important;}
#${SVG_ID} .cluster rect{fill:transparent !important;stroke:currentColor !important;stroke-opacity:0.4 !important;stroke-dasharray:6 5 !important;}
#${SVG_ID} .cluster text,#${SVG_ID} .cluster tspan,#${SVG_ID} .cluster-label,#${SVG_ID} .cluster-label text,#${SVG_ID} .cluster-label tspan{fill:currentColor !important;}
#${SVG_ID} .edgeLabel,#${SVG_ID} .edgeLabel p{background-color:transparent !important;}
#${SVG_ID} .edgeLabel rect{fill:transparent !important;opacity:0 !important;}
#${SVG_ID} .edgeLabel text,#${SVG_ID} .edgeLabel tspan{fill:currentColor !important;}
</style>`;
svg = svg.replace(/<\/svg>\s*$/, themeStyle + '</svg>');

// 3) Header comment (provenance; regenerate with `npm run sync:graph`). Kept out of the <svg>
//    element so inlining stays clean.
const header = `<!-- GENERATED by scripts/build_graph_svg.mjs from site/src/data/vaults_graph.mmd — do not edit by hand; run \`npm run sync:graph\`. ${vaultCount} vaults, ${edgeCount} edges. -->\n`;
const output = header + svg + '\n';

// --- Idempotency guard: write only when the render actually changed ---------------------------
const sizeKB = Math.round(Buffer.byteLength(output, 'utf-8') / 1024);
const prev = fs.existsSync(OUTPUT_SVG) ? fs.readFileSync(OUTPUT_SVG, 'utf-8') : null;
const textCount = (svg.match(/<text\b/g) || []).length;

if (prev === output) {
  console.log(`[build_graph_svg] no change — vaults_graph.svg already current (${sizeKB} KB, ${textCount} <text> labels, ${vaultCount} vaults / ${edgeCount} edges).`);
} else {
  fs.mkdirSync(path.dirname(OUTPUT_SVG), { recursive: true });
  fs.writeFileSync(OUTPUT_SVG, output);
  console.log(`[build_graph_svg] wrote ${OUTPUT_SVG} (${sizeKB} KB, ${textCount} <text> labels, ${vaultCount} vaults / ${edgeCount} edges).`);
}
if (sizeKB > 500) {
  console.warn(`[build_graph_svg] WARN: output is ${sizeKB} KB (> 500 KB budget) — consider a leaner mermaid config.`);
}

process.exit(0);
