/**
 * gate-32 — spec split integrity (HAUSSMANN P2.3 O1).
 *
 * `src/content/spec/*.mdx` is a GENERATED projection of `reference/specification.mdx`, which is
 * itself a projection of `.adna/what/docs/adna_standard.md`. A two-stage projection has two ways
 * to rot quietly: someone edits a section file by hand (lost on the next split), or someone
 * updates the spec and forgets to re-split (the site then serves a stale standard while claiming
 * a version number it no longer matches). Neither shows up as a build error.
 *
 * So this gate does not check that the pages render. It checks that the parts still ARE the
 * source: run the splitter in --check mode, and separately assert the section bodies reconstitute
 * the spec body verbatim.
 */
import { test, expect } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const SITE_ROOT = process.cwd();
const SPEC = join(SITE_ROOT, 'src/content/reference/specification.mdx');
const SECTIONS_DIR = join(SITE_ROOT, 'src/content/spec');

/** Strip frontmatter and the generated-file banner; leave the prose. */
function bodyOf(mdx: string): string {
  const withoutFm = mdx.replace(/^---\n[\s\S]*?\n---\n/, '');
  return withoutFm.replace(/\{\/\*\s*GENERATED by[\s\S]*?\*\/\}/, '').trim();
}

test.describe('gate-32 spec split integrity', () => {
  test('the split is current with its source', () => {
    expect(existsSync(SECTIONS_DIR), 'src/content/spec is missing — run the splitter').toBe(true);
    // Throws (non-zero exit) listing MISSING / STALE / ORPHAN files if anything drifted.
    const out = execFileSync('node', ['scripts/split_specification.mjs', '--check'], {
      cwd: SITE_ROOT,
      encoding: 'utf8',
    });
    expect(out).toContain('spec split is current');
  });

  test('the sections reconstitute the specification body verbatim', () => {
    const files = readdirSync(SECTIONS_DIR)
      .filter((f) => f.endsWith('.mdx'))
      .sort(); // zero-padded filenames sort into document order
    expect(files.length, 'expected the generated section files').toBeGreaterThan(0);

    const specBody = bodyOf(readFileSync(SPEC, 'utf8'));

    // Every section's prose must appear in the source, in order, with nothing invented.
    let cursor = 0;
    const missing: string[] = [];
    for (const f of files) {
      const section = bodyOf(readFileSync(join(SECTIONS_DIR, f), 'utf8'));
      // The splitter removes the section's own `## N. Title` line; compare on the remainder.
      const probe = section.split('\n').find((l) => l.trim().length > 20) ?? section.slice(0, 80);
      const at = specBody.indexOf(probe.trim(), cursor);
      if (at === -1) missing.push(f);
      else cursor = at;
    }
    expect(
      missing,
      `section content not found in specification.mdx, or out of order — the split is stale or hand-edited: ${missing.join(', ')}`,
    ).toEqual([]);
  });

  test('every section file declares itself generated', () => {
    const files = readdirSync(SECTIONS_DIR).filter((f) => f.endsWith('.mdx'));
    const undeclared = files.filter(
      (f) => !readFileSync(join(SECTIONS_DIR, f), 'utf8').includes('GENERATED by scripts/split_specification.mjs'),
    );
    expect(
      undeclared,
      `section files with no generated-by banner — a reader would take these for hand-authored: ${undeclared.join(', ')}`,
    ).toEqual([]);
  });

  test('section numbering is dense, ascending, and matches the built routes', () => {
    const files = readdirSync(SECTIONS_DIR).filter((f) => f.endsWith('.mdx')).sort();
    const numbers = files.map((f) => Number(readFileSync(join(SECTIONS_DIR, f), 'utf8').match(/^number:\s*(\d+)/m)![1]));
    expect(numbers, 'section numbers must be 1..N with no gaps').toEqual(
      Array.from({ length: files.length }, (_, i) => i + 1),
    );

    const dist = join(SITE_ROOT, 'dist/reference/specification');
    test.skip(!existsSync(dist), 'no dist/ — site not built');
    const built = readdirSync(dist, { withFileTypes: true })
      .filter((e) => e.isDirectory() && e.name !== 'full')
      .map((e) => e.name);
    expect(
      built.length,
      'built section route count must match the generated section count',
    ).toBe(files.length);
  });
});
